<?php

namespace AppBundle\Repository;

/**
 * FabricantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabricantRepository extends \Doctrine\ORM\EntityRepository
{
}
